# Installing and Using Pandas

In [3]:
import pandas as pd
import numpy as np
print('Pandas version:',pd.__version__ )
print('NumPy version:',np.__version__ )

Pandas version: 1.5.3
NumPy version: 1.24.2


# Introducing Panda Objects

## Pandas Series Objects

In [13]:
data = pd.Series([2.5, 3.14, 'Tacos', 7])

print(data)

0      2.5
1     3.14
2    Tacos
3        7
dtype: object


### Series as NumPy array

In [37]:
data = pd.Series([0, 2.5, 5, 7.5, 10],
                 index=['1.', '2.', '3.', '4.', '5.'])

print('The whole series:\n', data)
print('\nThe specified series:', data['3.'])

The whole series:
 1.     0.0
2.     2.5
3.     5.0
4.     7.5
5.    10.0
dtype: float64

The specified series: 5.0


### Series as specialized dictionary

In [14]:
homeruns_dict = {'Barry Bonds': 762,
                'Hank Aaron': 755,
                'Babe Ruth': 714,
                'Albert Pujols': 703,
                'Alex Rodriguez': 696,
                'Willie Mays' : 660,
                'Ken Griffey Jr.' : 630,
                'Jim Thome' : 612,
                'Sammy Sosa' : 609,
                'Frank Robinson' : 586
                }
homeruns = pd.Series(homeruns_dict)
print('Top three homerun hitters:\n',homeruns['Barry Bonds': 'Babe Ruth'])

Top three homerun hitters:
 Barry Bonds    762
Hank Aaron     755
Babe Ruth      714
dtype: int64


### Constructing series objects

In [9]:
P = pd.Series({'x': 100, 'y': 200, 'z': 300}, index=['z', 'y'])
print('The desired index is:\n',P)

The desired index is:
 z    300
y    200
dtype: int64


## The Pandas DataFrame Object

### DataFrame as NumPy array

In [30]:
hits_dict = {'Barry Bonds': 2935,
                'Hank Aaron': 3771,
                'Babe Ruth': 2873,
                'Albert Pujols': 3384,
                'Alex Rodriguez': 3115,
                'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781,
                'Jim Thome' : 2328,
                'Sammy Sosa' : 2408,
                'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

players = pd.DataFrame({'Homeruns': homeruns,
                        'Hits': hits})
print('The best baseball players are:')
players

The best baseball players are:


Homeruns  Hits
Barry Bonds           762  2935
Hank Aaron            755  3771
Babe Ruth             714  2873
Albert Pujols         703  3384
Alex Rodriguez        696  3115
Willie Mays           660  3283
Ken Griffey Jr.       630  2781
Jim Thome             612  2328
Sammy Sosa            609  2408
Frank Robinson        586  2943

### Constructing DataFrame objects

In [48]:
pd.DataFrame([{'a': 3, 'b': 2, 'c':1}, {'a':4,'b': 5, 'c': 6}],
             columns=['a', 'b', 'c'],
             index=['Row 1', 'Row 2'])

a  b  c
Row 1  3  2  1
Row 2  4  5  6

## Pandas index object

### Index as immutable array

In [55]:
i = pd.Index([6, 3.0, 9.4, 'tacos', 7])
print('The index from the third value on:\n',i[2:])

The index from the third value on:
 Index([9.4, 'tacos', 7], dtype='object')


In [57]:
# The array can't be changed
i[2] = 99

TypeError: Index does not support mutable operations

### Index as ordered set

In [67]:
I1 = pd.Index([7, 5, 4, 3, 6])
I2 = pd.Index([1, 5, 4, 3, 2])

print('Union of the indexes:',I1.union(I2))
print('Intersection of the indexes:',I1.intersection(I2))
print('Diffferences of the indexes:',I1.symmetric_difference(I2))

Union of the indexes: Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')
Intersection of the indexes: Index([5, 4, 3], dtype='int64')
Diffferences of the indexes: Index([1, 2, 6, 7], dtype='int64')


# Data Indexing and Selection

## Data Selection in series

### Series as dictionary

In [102]:
players = pd.DataFrame({'Homeruns': homeruns,
                        'Hits': hits})
print('The best baseball players are:')
print('Here are the hits for all the players:\n',players['Hits'])


The best baseball players are:
Here are the hits for all the players:
 Barry Bonds        2935
Hank Aaron         3771
Babe Ruth          2873
Albert Pujols      3384
Alex Rodriguez     3115
Willie Mays        3283
Ken Griffey Jr.    2781
Jim Thome          2328
Sammy Sosa         2408
Frank Robinson     2943
Name: Hits, dtype: int64


### Series as 1D array

In [111]:
print('Players that have 3000 hits and 700 homeruns:')
players[(homeruns > 700) & (hits > 2800)]

Players that have 3000 hits and 700 homeruns:


Homeruns  Hits
Barry Bonds         762  2935
Hank Aaron          755  3771
Babe Ruth           714  2873
Albert Pujols       703  3384

### Indexers: loc, iloc and ix

In [140]:
data = pd.Series(['Hank Aaron    ', 'Albert Pujols', 'Barry Bonds  ']
                 , index=[1, 2, 3])
print('The top three players in baseball:\n', data)

print('Here\n',data.iloc[0])

The top three players in baseball:
 1    Hank Aaron    
2     Albert Pujols
3     Barry Bonds  
dtype: object
Here
 1    Hank Aaron    
2     Albert Pujols
dtype: object


In [9]:
AB_dict = {'Barry Bonds': 9847, 'Hank Aaron': 12364,
                'Babe Ruth': 8399, 'Albert Pujols': 11421,
                'Alex Rodriguez': 10566, 'Willie Mays' : 10881,
                'Ken Griffey Jr.' : 9801, 'Jim Thome' : 8422,
                'Sammy Sosa' : 8813, 'Frank Robinson' : 10006
            }
AB = pd.Series(AB_dict)

hits_dict = {'Barry Bonds': 2935, 'Hank Aaron': 3771,
                'Babe Ruth': 2873, 'Albert Pujols': 3384,
                'Alex Rodriguez': 3115, 'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781, 'Jim Thome' : 2328,
                'Sammy Sosa' : 2408, 'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

players = pd.DataFrame({'Hits': hits,
                        'AB': AB})
print('The best baseball players are:')
players['BAA'] = players['Hits'] / players['AB']
players.T

The best baseball players are:


Barry Bonds    Hank Aaron    Babe Ruth  Albert Pujols  Alex Rodriguez  \
Hits   2935.00000   3771.000000  2873.000000    3384.000000     3115.000000   
AB     9847.00000  12364.000000  8399.000000   11421.000000    10566.000000   
BAA       0.29806      0.304998     0.342065       0.296296        0.294814   

       Willie Mays  Ken Griffey Jr.    Jim Thome   Sammy Sosa  Frank Robinson  
Hits   3283.000000      2781.000000  2328.000000  2408.000000     2943.000000  
AB    10881.000000      9801.000000  8422.000000  8813.000000    10006.000000  
BAA       0.301719         0.283747     0.276419     0.273233        0.294124

### Additional Indexing conventions

In [10]:
players[players.BAA > .300]

Hits     AB       BAA
Hank Aaron   3771  12364  0.304998
Babe Ruth    2873   8399  0.342065
Willie Mays  3283  10881  0.301719

# Operating on Data in Pandas


## Ufuncs: Index Preservation

In [27]:
r = np.random.RandomState(99)
array = pd.DataFrame(r.randint(0, 20, (5, 5)),
        columns=['A', 'B', 'C', 'D', 'E'])
print('Here is the e^r 5x5 array:')
np.exp(array)

Here is the e^r 5x5 array:


A             B             C            D             E
0  2.718282e+00  2.008554e+01  2.980958e+03  8103.083928  2.980958e+03
1  6.565997e+07  5.459815e+01  1.484132e+02     2.718282  2.008554e+01
2  2.415495e+07  2.718282e+00  8.886111e+06   403.428793  5.987414e+04
3  7.389056e+00  1.000000e+00  1.627548e+05  2980.957987  2.980958e+03
4  1.096633e+03  3.269017e+06  3.269017e+06   148.413159  1.202604e+06

### Ufuncs: Index Alignment

In [37]:
homeruns_dict = {'Barry Bonds': 762, 'Hank Aaron': 755,
                'Babe Ruth': 714, 'Albert Pujols': 703,
                'Alex Rodriguez': 696, 'Willie Mays' : 660,
                'Ken Griffey Jr.' : 630, 'Jim Thome' : 612,
                'Sammy Sosa' : 609, 'Frank Robinson' : 586
                }
homeruns = pd.Series(homeruns_dict)

hits_dict = {'Pete Rose': 4256, 'Hank Aaron': 3771,
                'Ty Cobb': 4189, 'Albert Pujols': 3384,
                'Stan Musial': 3630, 'Tris Speaker' : 3514,
                'Honus Wagner' : 3430, 'Derek Jeter' : 3465,
                'Willie Mays' : 3283, 'Paul Molitor' : 3319
                }
hits = pd.Series(hits_dict)

homeruns.index | hits.index

/tmp/ipykernel_9764/4277536936.py:17: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  homeruns.index | hits.index


Index(['Albert Pujols', 'Alex Rodriguez', 'Babe Ruth', 'Barry Bonds',
       'Derek Jeter', 'Frank Robinson', 'Hank Aaron', 'Honus Wagner',
       'Jim Thome', 'Ken Griffey Jr.', 'Paul Molitor', 'Pete Rose',
       'Sammy Sosa', 'Stan Musial', 'Tris Speaker', 'Ty Cobb', 'Willie Mays'],
      dtype='object')

In [41]:
hits_dict = {'Barry Bonds': 2935, 'Hank Aaron': 3771,
                'Babe Ruth': 2873, 'Albert Pujols': 3384,
                'Alex Rodriguez': 3115, 'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781, 'Jim Thome' : 2328,
                'Sammy Sosa' : 2408, 'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

print('The rate of hits before a homerun:\n',hits / homeruns)

The rate of hits before a homerun:
 Barry Bonds        3.851706
Hank Aaron         4.994702
Babe Ruth          4.023810
Albert Pujols      4.813656
Alex Rodriguez     4.475575
Willie Mays        4.974242
Ken Griffey Jr.    4.414286
Jim Thome          3.803922
Sammy Sosa         3.954023
Frank Robinson     5.022184
dtype: float64


In [43]:
print('How many hits were not homeruns:\n',hits.subtract(homeruns, fill_value=0))

How many hits were not homeruns:
 Barry Bonds        2173
Hank Aaron         3016
Babe Ruth          2159
Albert Pujols      2681
Alex Rodriguez     2419
Willie Mays        2623
Ken Griffey Jr.    2151
Jim Thome          1716
Sammy Sosa         1799
Frank Robinson     2357
dtype: int64


## Ufuncs: Operations Between DataFrame and Series

In [53]:
N = r.randint(20, size=(5, 5))
print('The orignal 5x5 array:\n', N)
print('The 5x5 array minus first value:\n', N - N[0,0])

The orignal 5x5 array:
 [[ 6  7  6  1  8]
 [ 8  4  2  2  6]
 [ 1 16  6  0 12]
 [ 1  3  5  9  1]
 [17  8 13 10 12]]
The 5x5 array minus first value:
 [[ 0  1  0 -5  2]
 [ 2 -2 -4 -4  0]
 [-5 10  0 -6  6]
 [-5 -3 -1  3 -5]
 [11  2  7  4  6]]
