# Installing and Using Pandas

In [2]:
import pandas as pd
import numpy as np
print('Pandas version:',pd.__version__ )
print('NumPy version:',np.__version__ )

Pandas version: 1.5.3
NumPy version: 1.24.2


# Introducing Panda Objects

## Pandas Series Objects

In [3]:
data = pd.Series([2.5, 3.14, 'Tacos', 7])

print(data)

0      2.5
1     3.14
2    Tacos
3        7
dtype: object


### Series as NumPy array

In [4]:
data = pd.Series([0, 2.5, 5, 7.5, 10],
                 index=['1.', '2.', '3.', '4.', '5.'])

print('The whole series:\n', data)
print('\nThe specified series:', data['3.'])

The whole series:
 1.     0.0
2.     2.5
3.     5.0
4.     7.5
5.    10.0
dtype: float64

The specified series: 5.0


### Series as specialized dictionary

In [5]:
homeruns_dict = {'Barry Bonds': 762,
                'Hank Aaron': 755,
                'Babe Ruth': 714,
                'Albert Pujols': 703,
                'Alex Rodriguez': 696,
                'Willie Mays' : 660,
                'Ken Griffey Jr.' : 630,
                'Jim Thome' : 612,
                'Sammy Sosa' : 609,
                'Frank Robinson' : 586
                }
homeruns = pd.Series(homeruns_dict)
print('Top three homerun hitters:\n',homeruns['Barry Bonds': 'Babe Ruth'])

Top three homerun hitters:
 Barry Bonds    762
Hank Aaron     755
Babe Ruth      714
dtype: int64


### Constructing series objects

In [6]:
P = pd.Series({'x': 100, 'y': 200, 'z': 300}, index=['z', 'y'])
print('The desired index is:\n',P)

The desired index is:
 z    300
y    200
dtype: int64


## The Pandas DataFrame Object

### DataFrame as NumPy array

In [7]:
hits_dict = {'Barry Bonds': 2935,
                'Hank Aaron': 3771,
                'Babe Ruth': 2873,
                'Albert Pujols': 3384,
                'Alex Rodriguez': 3115,
                'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781,
                'Jim Thome' : 2328,
                'Sammy Sosa' : 2408,
                'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

players = pd.DataFrame({'Homeruns': homeruns,
                        'Hits': hits})
print('The best baseball players are:')
players

The best baseball players are:


Homeruns  Hits
Barry Bonds           762  2935
Hank Aaron            755  3771
Babe Ruth             714  2873
Albert Pujols         703  3384
Alex Rodriguez        696  3115
Willie Mays           660  3283
Ken Griffey Jr.       630  2781
Jim Thome             612  2328
Sammy Sosa            609  2408
Frank Robinson        586  2943

### Constructing DataFrame objects

In [8]:
pd.DataFrame([{'a': 3, 'b': 2, 'c':1}, {'a':4,'b': 5, 'c': 6}],
             columns=['a', 'b', 'c'],
             index=['Row 1', 'Row 2'])

a  b  c
Row 1  3  2  1
Row 2  4  5  6

## Pandas index object

### Index as immutable array

In [9]:
i = pd.Index([6, 3.0, 9.4, 'tacos', 7])
print('The index from the third value on:\n',i[2:])

The index from the third value on:
 Index([9.4, 'tacos', 7], dtype='object')


In [10]:
# The array can't be changed
i[2] = 99

TypeError: Index does not support mutable operations

### Index as ordered set

In [ ]:
I1 = pd.Index([7, 5, 4, 3, 6])
I2 = pd.Index([1, 5, 4, 3, 2])

print('Union of the indexes:',I1.union(I2))
print('Intersection of the indexes:',I1.intersection(I2))
print('Diffferences of the indexes:',I1.symmetric_difference(I2))

Union of the indexes: Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')
Intersection of the indexes: Index([5, 4, 3], dtype='int64')
Diffferences of the indexes: Index([1, 2, 6, 7], dtype='int64')


# Data Indexing and Selection

## Data Selection in series

### Series as dictionary

In [ ]:
players = pd.DataFrame({'Homeruns': homeruns,
                        'Hits': hits})
print('The best baseball players are:')
print('Here are the hits for all the players:\n',players['Hits'])


The best baseball players are:
Here are the hits for all the players:
 Barry Bonds        2935
Hank Aaron         3771
Babe Ruth          2873
Albert Pujols      3384
Alex Rodriguez     3115
Willie Mays        3283
Ken Griffey Jr.    2781
Jim Thome          2328
Sammy Sosa         2408
Frank Robinson     2943
Name: Hits, dtype: int64


### Series as 1D array

In [ ]:
print('Players that have 3000 hits and 700 homeruns:')
players[(homeruns > 700) & (hits > 2800)]

Players that have 3000 hits and 700 homeruns:


Homeruns  Hits
Barry Bonds         762  2935
Hank Aaron          755  3771
Babe Ruth           714  2873
Albert Pujols       703  3384

### Indexers: loc, iloc and ix

In [ ]:
data = pd.Series(['Hank Aaron    ', 'Albert Pujols', 'Barry Bonds  ']
                 , index=[1, 2, 3])
print('The top three players in baseball:\n', data)

print('Here\n',data.iloc[0])

The top three players in baseball:
 1    Hank Aaron    
2     Albert Pujols
3     Barry Bonds  
dtype: object
Here
 1    Hank Aaron    
2     Albert Pujols
dtype: object


In [ ]:
AB_dict = {'Barry Bonds': 9847, 'Hank Aaron': 12364,
                'Babe Ruth': 8399, 'Albert Pujols': 11421,
                'Alex Rodriguez': 10566, 'Willie Mays' : 10881,
                'Ken Griffey Jr.' : 9801, 'Jim Thome' : 8422,
                'Sammy Sosa' : 8813, 'Frank Robinson' : 10006
            }
AB = pd.Series(AB_dict)

hits_dict = {'Barry Bonds': 2935, 'Hank Aaron': 3771,
                'Babe Ruth': 2873, 'Albert Pujols': 3384,
                'Alex Rodriguez': 3115, 'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781, 'Jim Thome' : 2328,
                'Sammy Sosa' : 2408, 'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

players = pd.DataFrame({'Hits': hits,
                        'AB': AB})
print('The best baseball players are:')
players['BAA'] = players['Hits'] / players['AB']
players.T

The best baseball players are:


Barry Bonds    Hank Aaron    Babe Ruth  Albert Pujols  Alex Rodriguez  \
Hits   2935.00000   3771.000000  2873.000000    3384.000000     3115.000000   
AB     9847.00000  12364.000000  8399.000000   11421.000000    10566.000000   
BAA       0.29806      0.304998     0.342065       0.296296        0.294814   

       Willie Mays  Ken Griffey Jr.    Jim Thome   Sammy Sosa  Frank Robinson  
Hits   3283.000000      2781.000000  2328.000000  2408.000000     2943.000000  
AB    10881.000000      9801.000000  8422.000000  8813.000000    10006.000000  
BAA       0.301719         0.283747     0.276419     0.273233        0.294124

### Additional Indexing conventions

In [ ]:
players[players.BAA > .300]

Hits     AB       BAA
Hank Aaron   3771  12364  0.304998
Babe Ruth    2873   8399  0.342065
Willie Mays  3283  10881  0.301719

# Operating on Data in Pandas


## Ufuncs: Index Preservation

In [ ]:
r = np.random.RandomState(99)
array = pd.DataFrame(r.randint(0, 20, (5, 5)),
        columns=['A', 'B', 'C', 'D', 'E'])
print('Here is the e^r 5x5 array:')
np.exp(array)

Here is the e^r 5x5 array:


A             B             C            D             E
0  2.718282e+00  2.008554e+01  2.980958e+03  8103.083928  2.980958e+03
1  6.565997e+07  5.459815e+01  1.484132e+02     2.718282  2.008554e+01
2  2.415495e+07  2.718282e+00  8.886111e+06   403.428793  5.987414e+04
3  7.389056e+00  1.000000e+00  1.627548e+05  2980.957987  2.980958e+03
4  1.096633e+03  3.269017e+06  3.269017e+06   148.413159  1.202604e+06

### Ufuncs: Index Alignment

In [ ]:
homeruns_dict = {'Barry Bonds': 762, 'Hank Aaron': 755,
                'Babe Ruth': 714, 'Albert Pujols': 703,
                'Alex Rodriguez': 696, 'Willie Mays' : 660,
                'Ken Griffey Jr.' : 630, 'Jim Thome' : 612,
                'Sammy Sosa' : 609, 'Frank Robinson' : 586
                }
homeruns = pd.Series(homeruns_dict)

hits_dict = {'Pete Rose': 4256, 'Hank Aaron': 3771,
                'Ty Cobb': 4189, 'Albert Pujols': 3384,
                'Stan Musial': 3630, 'Tris Speaker' : 3514,
                'Honus Wagner' : 3430, 'Derek Jeter' : 3465,
                'Willie Mays' : 3283, 'Paul Molitor' : 3319
                }
hits = pd.Series(hits_dict)

homeruns.index | hits.index

/tmp/ipykernel_9764/4277536936.py:17: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  homeruns.index | hits.index


Index(['Albert Pujols', 'Alex Rodriguez', 'Babe Ruth', 'Barry Bonds',
       'Derek Jeter', 'Frank Robinson', 'Hank Aaron', 'Honus Wagner',
       'Jim Thome', 'Ken Griffey Jr.', 'Paul Molitor', 'Pete Rose',
       'Sammy Sosa', 'Stan Musial', 'Tris Speaker', 'Ty Cobb', 'Willie Mays'],
      dtype='object')

In [ ]:
hits_dict = {'Barry Bonds': 2935, 'Hank Aaron': 3771,
                'Babe Ruth': 2873, 'Albert Pujols': 3384,
                'Alex Rodriguez': 3115, 'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781, 'Jim Thome' : 2328,
                'Sammy Sosa' : 2408, 'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

print('The rate of hits before a homerun:\n',hits / homeruns)

The rate of hits before a homerun:
 Barry Bonds        3.851706
Hank Aaron         4.994702
Babe Ruth          4.023810
Albert Pujols      4.813656
Alex Rodriguez     4.475575
Willie Mays        4.974242
Ken Griffey Jr.    4.414286
Jim Thome          3.803922
Sammy Sosa         3.954023
Frank Robinson     5.022184
dtype: float64


In [ ]:
print('How many hits were not homeruns:\n',hits.subtract(homeruns, fill_value=0))

How many hits were not homeruns:
 Barry Bonds        2173
Hank Aaron         3016
Babe Ruth          2159
Albert Pujols      2681
Alex Rodriguez     2419
Willie Mays        2623
Ken Griffey Jr.    2151
Jim Thome          1716
Sammy Sosa         1799
Frank Robinson     2357
dtype: int64


## Ufuncs: Operations Between DataFrame and Series

In [ ]:
N = r.randint(20, size=(5, 5))
print('The orignal 5x5 array:\n', N)
print('The 5x5 array minus first value:\n', N - N[0,0])

M = pd.DataFrame(N, columns=list('ABCDE'))
M.subtract(M['C'], axis=0)


The orignal 5x5 array:
 [[ 3 11  6  7  9]
 [ 2  7  5  1 16]
 [ 2  7  0  6 18]
 [ 8  4 18 13 15]
 [ 0  1 16 11  3]]
The 5x5 array minus first value:
 [[ 0  8  3  4  6]
 [-1  4  2 -2 13]
 [-1  4 -3  3 15]
 [ 5  1 15 10 12]
 [-3 -2 13  8  0]]


A   B  C  D   E
0  -3   5  0  1   3
1  -3   2  0 -4  11
2   2   7  0  6  18
3 -10 -14  0 -5  -3
4 -16 -15  0 -5 -13

# Handling Missing Data

## Missing Data in Pandas

### Pythonic missing data

In [ ]:
X1 = np.array([7, 3.14, 4 + 3j, 8])
print('The sum of the first array:',X1.sum())

X2 = np.array([7, 3.14, 4 + 3j, None])
print('The sum of the second array:',X2.sum())

The sum of the first array: (22.14+3j)


TypeError: unsupported operand type(s) for +: 'complex' and 'NoneType'

### Missing numerical data

In [ ]:
Y = np.array([7, np.nan, 3.14, 4+ 3j]) 
print('Result of calculations including nan:\n',Y.sum(), Y.min(), Y.max())
print('Result of calculations excluding nan:\n',np.nansum(Y), np.nanmin(Y), np.nanmax(Y))


Result of calculations including nan:
 (nan+3j) (nan+0j) (nan+0j)
Result of calculations excluding nan:
 (14.14+3j) (3.14+0j) (7+0j)


### NaN and None in Pandas

In [ ]:
pd.Series([7, np.nan, 3.14, None])

0    7.00
1     NaN
2    3.14
3     NaN
dtype: float64

## Operating on null values

### Detecting null values

In [ ]:
data = pd.Series([7, np.nan, 'tacos', None])
print('The value types in the series:\n',data[data.notnull()])
print('\nThe null types in the series:\n',data[data.isnull()])


The value types in the series:
 0        7
2    tacos
dtype: object

The null types in the series:
 1     NaN
3    None
dtype: object


### Dropping null values

In [ ]:
data = pd.DataFrame([[3,      np.nan, 4],
                   [7,      8,     3.14],
                   [np.nan, 1,      0]])
print('Array with null backfilled:\n',data.fillna(method='bfill'))
print('\nArray with null frontfilled:\n',data.fillna(method='ffill'))


Array with null backfilled:
      0    1     2
0  3.0  8.0  4.00
1  7.0  8.0  3.14
2  NaN  1.0  0.00

Array with null frontfilled:
      0    1     2
0  3.0  NaN  4.00
1  7.0  8.0  3.14
2  7.0  1.0  0.00


# Hierarchical Indexing

## A Multiply indexed series

### Pandas MultiIndex

In [ ]:
Teams = [('LA Dodgers', 2020), ('Houston Astros', 2017),
         ('Washington Nationals', 2019), ('Boston RedSox', 2018),
         ('LA Dodgers', 2018), ('Houston Astros', 2019),
         ('LA Dodgers', 2017), ('Tampa Bay Rays', 2020)]
Wins = [43, 101,
       93, 108,
       92, 107,
       104, 40]
Winner = pd.Series(Wins, index=Teams)
#Winner = Winner.reindex(Teams)
Winner


(LA Dodgers, 2020)               43
(Houston Astros, 2017)          101
(Washington Nationals, 2019)     93
(Boston RedSox, 2018)           108
(LA Dodgers, 2018)               92
(Houston Astros, 2019)          107
(LA Dodgers, 2017)              104
(Tampa Bay Rays, 2020)           40
dtype: int64

In [ ]:
Winner_df = Winner.unstack()
Winner_df

ValueError: index must be a MultiIndex to unstack, <class 'pandas.core.indexes.base.Index'> was passed

## Methods of MultiIndex creation

In [ ]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.216691  0.996926
  2  0.772459  0.855296
b 1  0.464916  0.290822
  2  0.544669  0.460006

# Combining Datasets: Concat and Append

In [11]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

## Recall: Concatenation of NumPy Arrays

In [14]:
x = [[1, 2],[3, 4]]
y = [[5, 6],[7, 8]]
np.concatenate([x, y], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Simple Concatenation with pd.concat

In [ ]:
s1 = pd.Series(['Barry Bonds', 'Hank Aaron', 'Albert Pujols'], index=[1, 2, 3])
s2 = pd.Series(['Derek Jeter', 'Pete Rose', 'Willie Mays'], index=[4, 5, 6])
pd.concat([s1, s2])

1      Barry Bonds
2       Hank Aaron
3    Albert Pujols
4      Derek Jeter
5        Pete Rose
6      Willie Mays
dtype: object

### Duplicate Indices

In [19]:
x = make_df('AB', [1, 2])
y = make_df('AB', [3, 4])
y.index = x.index  # make duplicate indices!
display('x', 'y', 'pd.concat([x, y])')

'x'

'y'

'pd.concat([x, y])'

#### Catching the repeats as an error

In [16]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Int64Index([1, 2], dtype='int64')


#### Ignoring the index

In [17]:
display('x', 'y', 'pd.concat([x, y])')

'x'

'y'

'pd.concat([x, y])'

#### Adding MultiIndex Keys

In [ ]:
display('x', 'y', "pd.concat([x, y], keys=['x', 'y'])")

x
    A   B
1  A1  B1
2  A2  B2

y
    B   C
1  B3  C3
2  B4  C4

pd.concat([x, y], keys=['x', 'y'])
       A   B    C
x 1   A1  B1  NaN
  2   A2  B2  NaN
y 1  NaN  B3   C3
  2  NaN  B4   C4

### Concatenation with joins

In [20]:
X1 = make_df('ABC', [1, 2, 3])
X2 = make_df('BCD', [4, 5, 6])
display('X1', 'X2', 'pd.concat([X1, X2])')

'X1'

'X2'

'pd.concat([X1, X2])'

In [ ]:
display('X1', 'X2',
        "pd.concat([X1, X2], join='inner')")

X1
    A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

X2
    B   C   D
4  B4  C4  D4
5  B5  C5  D5
6  B6  C6  D6

pd.concat([X1, X2], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
5  B5  C5
6  B6  C6

# Combining Datasets: Merge and Join

## Categories of joibs

### One to one joins

In [23]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

'df1'

'df2'

In [22]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

### Many to one joins

In [24]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
display('df3', 'df4', 'pd.merge(df3, df4)')

'df3'

'df4'

'pd.merge(df3, df4)'

### Many to many joins

In [ ]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                              'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})
display('df1', 'df5', "pd.merge(df1, df5)")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df5
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

pd.merge(df1, df5)
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

## Specification of the merge key

### The on keyword

In [ ]:
display('df1', 'df2', "pd.merge(df1, df2, on='employee')")

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

pd.merge(df1, df2, on='employee')
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

### The left_on and right_on keywords

In [ ]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
display('df1', 'df3', 'pd.merge(df1, df3, left_on="employee", right_on="name")')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1, df3, left_on="employee", right_on="name")
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [ ]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

### The left_index and right_index keywords

In [ ]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
display('df1a', 'df2a')

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [ ]:
display('df1a', 'df2a',
        "pd.merge(df1a, df2a, left_index=True, right_index=True)")

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

pd.merge(df1a, df2a, left_index=True, right_index=True)
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [ ]:
display('df1a', 'df2a', 'df1a.join(df2a)')

df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

df1a.join(df2a)
                group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [ ]:
display('df1a', 'df3', "pd.merge(df1a, df3, left_index=True, right_on='name')")


df1a
                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

df3
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

pd.merge(df1a, df3, left_index=True, right_on='name')
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

## Specifying set arithmetic for joins

In [ ]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
display('df6', 'df7', 'pd.merge(df6, df7)')

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7)
   name   food drink
0  Mary  bread  wine

In [ ]:
pd.merge(df6, df7, how='inner')

name   food drink
0  Mary  bread  wine

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='outer')")

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7, how='outer')
     name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [ ]:
display('df6', 'df7', "pd.merge(df6, df7, how='left')")

df6
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df7
     name drink
0    Mary  wine
1  Joseph  beer

pd.merge(df6, df7, how='left')
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

## Overlapping Columns Names: The suffixes keyword

In [ ]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
display('df8', 'df9', 'pd.merge(df8, df9, on="name")')

df8
   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

df9
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

pd.merge(df8, df9, on="name")
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [ ]:
display('df8', 'df9', 'pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])')

df8
   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

df9
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

pd.merge(df8, df9, on="name", suffixes=["_L", "_R"])
   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

# Aggregation and Grouping

## Planets Data

In [ ]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [ ]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

## Simple Aggregation in Pandas

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
print(ser)
print(ser.sum())
print(ser.mean())

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64
2.811925491708157
0.5623850983416314


In [ ]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
print(df)
print('\n',df.mean())
print('\n',df.mean(axis='columns'))

          A         B
0  0.183405  0.611853
1  0.304242  0.139494
2  0.524756  0.292145
3  0.431945  0.366362
4  0.291229  0.456070

 A    0.347115
B    0.373185
dtype: float64

 0    0.397629
1    0.221868
2    0.408451
3    0.399153
4    0.373650
dtype: float64


In [ ]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

## GroupBy: Split, Apply, Combine

### Split, Apply, Combine

In [ ]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [ ]:
df.groupby('key')

In [ ]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

### The GroupBy object

#### Column indexing

In [ ]:
planets.groupby('method')

In [ ]:
planets.groupby('method')['orbital_period']

In [ ]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

#### Iteration over groups

In [ ]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)


#### Dispatch methods

In [ ]:
planets.groupby('method')['year'].describe().unstack()

       method                       
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...  
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

### Aggregate, filter, transform, apply

In [ ]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                   columns = ['key', 'data1', 'data2'])
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

#### Aggregation

In [ ]:
df.groupby('key').aggregate(['min', np.median, max])

C:\Users\zscon\AppData\Local\Temp\ipykernel_19620\968873422.py:1: FutureWarning: The provided callable <function median at 0x00000158FA389DA0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('key').aggregate(['min', np.median, max])
C:\Users\zscon\AppData\Local\Temp\ipykernel_19620\968873422.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('key').aggregate(['min', np.median, max])


data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [ ]:
df.groupby('key').aggregate({'data1': 'min',
                             'data2': 'max'})

data1  data2
key              
A        0      5
B        1      7
C        2      9

#### Filtering

In [ ]:
def filter_func(x):
    return x['data2'].std() > 4

display('df', "df.groupby('key').std()", "df.groupby('key').filter(filter_func)")

df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby('key').std()
       data1     data2
key                   
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

df.groupby('key').filter(filter_func)
  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

#### Transformation

In [ ]:
df.groupby('key').transform(lambda x: x - x.mean())

data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

#### The apply() method

In [ ]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

display('df', "df.groupby('key').apply(norm_by_data2)")

<string>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
<string>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.


df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby('key').apply(norm_by_data2)
      key     data1  data2
key                       
A   0   A  0.000000      5
    3   A  0.375000      3
B   1   B  0.142857      0
    4   B  0.571429      7
C   2   C  0.166667      3
    5   C  0.416667      9

### Specifying the split key

In [ ]:
L = [0, 1, 0, 1, 2, 0]
display('df', 'df.groupby(L).sum()')

df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby(L).sum()
   key  data1  data2
0  ACC      7     17
1   BA      4      3
2    B      4      7

In [ ]:
display('df', "df.groupby(df['key']).sum()")

df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby(df['key']).sum()
     data1  data2
key              
A        3      8
B        5      7
C        7     12

#### A dictionary or series mapping index to group

In [ ]:
df2 = df.set_index('key')
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant'}
display('df2', 'df2.groupby(mapping).sum()')

df2
     data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9

df2.groupby(mapping).sum()
           data1  data2
key                    
consonant     12     19
vowel          3      8

#### Any Python Function

In [ ]:
display('df2', 'df2.groupby(str.lower).mean()')

df2
     data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9

df2.groupby(str.lower).mean()
     data1  data2
key              
a      1.5    4.0
b      2.5    3.5
c      3.5    6.0

#### A list of valid keys

In [ ]:
df2.groupby([str.lower, mapping]).mean()

data1  data2
key key                    
a   vowel        1.5    4.0
b   consonant    2.5    3.5
c   consonant    3.5    6.0

### Grouping example

In [ ]:
decade = 10 * (planets['year'] // 10)
decade = decade.astype(str) + 's'
decade.name = 'decade'
planets.groupby(['method', decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0